application:
  kafka:
    topics:
      first: "firstTopic"
      second: "secondTopic"
      third: "thirdTopic"
      fourth: "fourthTopic"

spring:
  kafka:
    bootstrap-servers: "localhost:29092"
    consumer:
      auto-offset-reset: earliest